---
spec/spec_helper.rb:
  spec_overrides:
    - "STASH_VERSION = '6.8.1'.freeze"
    - "BACKUP_VERSION = '3.3.2'.freeze"
    - "BITBUCKET_VERSION = '4.0.2'.freeze"
    - "BITBUCKET_BACKUP_VERSION = '2.0.0'.freeze"
